name: KOSIS Data Update  # 워크플로우 이름

on:
  schedule:
    - cron: "0 16 * * *"  # 매일 UTC 16:00 → 한국시간(KST) 01:00 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  run-script:
    runs-on: ubuntu-latest  # 실행 환경 (리눅스)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 코드 가져오기

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # 원하는 파이썬 버전 지정

      - name: Install dependencies
        run: pip install -r requirements.txt  # 필요하면 패키지 설치

      - name: Run KOSIS script
        run: python github_kosis_20250218.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
          KOSIS_API_KEY: ${{ secrets.KOSIS_API_KEY }}
          
      - name: Run RSS script
        run: python github_rss_20250219.py
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Run HTML Scraping script
        run: python github_html_20250219.py
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Run HTML Click Scraping script
        run: python github_html_onclick_20250219.py
        env:
          TOKEN: ${{ secrets.TOKEN }}          

      - name: Run HTML HREF Scraping script
        run: python github_html_href_20250219.py
        env:
          TOKEN: ${{ secrets.TOKEN }}          
